<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CentrosdeconsumoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('centrosdeconsumo')->insert([
            ['id' => 1, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 1],
            ['id' => 2, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 2],
            ['id' => 3, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 3],
            ['id' => 4, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 4],
            ['id' => 5, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 5],
            ['id' => 6, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 6],
            ['id' => 7, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 7],
            ['id' => 8, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 8],
            ['id' => 9, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 9],
            ['id' => 10, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 10],
            ['id' => 11, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 11],
            ['id' => 12, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 12],
            ['id' => 13, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 13],
            ['id' => 14, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 14],
            ['id' => 15, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 15],
            ['id' => 16, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 16],
            ['id' => 17, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 17],
            ['id' => 18, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 18],
            ['id' => 19, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 19],
            ['id' => 20, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 20],
            ['id' => 21, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 21],
            ['id' => 22, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 22],
            ['id' => 23, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 23],
            ['id' => 24, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 24],
            ['id' => 25, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 25],
            ['id' => 26, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 26],
            ['id' => 27, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 27],
            ['id' => 28, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 28],
            ['id' => 29, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 29],
            ['id' => 30, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 30],
            ['id' => 31, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 31],
            ['id' => 32, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 32],
            ['id' => 33, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 33],
            ['id' => 34, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 34],
            ['id' => 35, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 35],
            ['id' => 36, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 36],
            ['id' => 37, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 37],
            ['id' => 38, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 38],
            ['id' => 39, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 39],
            ['id' => 40, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 40],
            ['id' => 41, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 41],
            ['id' => 42, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 42],
            ['id' => 43, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 43],
            ['id' => 44, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 44],
            ['id' => 45, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 45],
            ['id' => 46, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 46],
            ['id' => 47, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 47],
            ['id' => 48, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 48],
            ['id' => 49, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 49],
            ['id' => 50, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 50],
            ['id' => 51, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 51],
            ['id' => 52, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 52],
            ['id' => 53, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 53],
            ['id' => 54, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 54],
            ['id' => 55, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 55],
            ['id' => 56, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 56],
            ['id' => 57, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 57],
            ['id' => 58, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 58],
            ['id' => 59, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 59],
            ['id' => 60, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 60],
            ['id' => 61, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 61],
            ['id' => 62, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 62],
            ['id' => 63, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 63],
            ['id' => 64, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 64],
            ['id' => 65, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 65],
            ['id' => 66, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 66],
            ['id' => 67, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 67],
            ['id' => 68, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 68],
            ['id' => 69, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 69],
            ['id' => 70, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 70],
            ['id' => 71, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 71],
            ['id' => 72, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 72],
            ['id' => 73, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 73],
            ['id' => 74, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 74],
            ['id' => 75, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 75],
            ['id' => 76, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 76],
            ['id' => 77, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 77],
            ['id' => 78, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 78],
            ['id' => 79, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 79],
            ['id' => 80, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 80],
            ['id' => 81, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 81],
            ['id' => 82, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 82],
            ['id' => 83, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 83],
            ['id' => 84, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 84],
            ['id' => 85, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 85],
            ['id' => 86, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 86],
            ['id' => 87, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 87],
            ['id' => 88, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 88],
            ['id' => 89, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 89],
            ['id' => 90, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 90],
            ['id' => 91, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 91],
            ['id' => 92, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 92],
            ['id' => 93, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 93],
            ['id' => 94, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 94],
            ['id' => 95, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 95],
            ['id' => 96, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 96],
            ['id' => 97, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 97],
            ['id' => 98, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 98],
            ['id' => 99, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 99],
            ['id' => 100, 'Propiedad' => 'Palacio Mundo Imperial', 'Centroconsumo' => 'Marche', 'Mesa' => 100],
        ]);
    }
}
